#!/bin/sh

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
target=${VIMRC_TARGET:-"$HOME/.vimrc"}
tmp_target="${target}.tmp.$$"

case "$(uname -s)" in
  Darwin) platform_file="$script_dir/mac" ;;
  MINGW*|MSYS*|CYGWIN*) platform_file="$script_dir/win" ;;
  *) platform_file="$script_dir/unix" ;;
esac

cleanup() {
  rm -f -- "$tmp_target"
}
trap cleanup EXIT HUP INT TERM

{
  printf '" Generated by %s; edit the source files instead.\n' "$script_dir/setup.sh"
  printf '" Platform: %s\n\n' "$(basename "$platform_file")"
  cat "$platform_file"
  printf '\n'
  cat "$script_dir/vimrc"
} > "$tmp_target"

chmod 600 "$tmp_target"
mv -- "$tmp_target" "$target"
trap - EXIT HUP INT TERM
printf 'Created %s from %s and vimrc\n' "$target" "$(basename "$platform_file")"
